### ISSUE TITLE
Cannot resolve module 'preact-compat/lib/ReactTransitionEvents'

### ISSUE THREAD

**Issue by Duan112358** [developit/preact-compat#123]
after set alias in webpack config

```
alias['react'] = 'preact-compat'
alias['react-dom'] = 'react-compat'
```

ERROR in ./~/react-slick/lib/mixins/helpers.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactTransitionEvents'
react-slick/lib/mixins 
@ ./~/react-slick/lib/mixins/helpers.js 17:37-79

**Comment by developit** [comment]
Hi @Duan112358 - currently, React's internals aren't supported by `preact-compat`, but I think this is a good place for us to start.  Normally I'd recommend a drop-in replacement module for you to alias out, but since what's being imported can be replicated in a few lines of code I think we should take the opportunity to start populating `preact-compat/lib/*`.  I'll submit a PR shortly.

**Comment by Duan112358** [comment]
Awesome.  At that time, react plugins should be shipped on `preact` elagently. 👍

**Comment by adriantoine** [comment]
That would be awesome!

**Comment by developit** [comment]
I just released `lib/ReactTransitionEvents` and `lib/ReactMount`!  Let me know if you are still seeing issues 💃
