### ISSUE TITLE
Uncaught ReferenceError: h is not defined

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat#161]
While migration somehow I need to add this
```js
import { h } from 'preact';
```
to avoid `Uncaught ReferenceError: h is not defined`
Is it normal?

And also I need to manually add `proptypes` to avoid error after that too.
Not sure this is expected behavior.

You can find the code [here](https://github.com/katopz/react-chartist-example/tree/webpack-preact-compat).
And I can reproduce by just comment out
```js
//import { h } from 'preact';
```
[here](https://github.com/katopz/react-chartist-example/blob/webpack-preact-compat/src/index.js#L1)

Thanks

**Comment by developit** [comment]
@katopz for preact-compat, instead of `h()` we use `preact-compat`'s `createElement()`:
https://github.com/katopz/react-chartist-example/blob/webpack-preact-compat/.babelrc#L9

You can actually change that line to drop the pragma entirely, making it use `React.createElement()`, which is already aliased! 🌈

**Comment by katopz** [comment]
@developit Cool! It did the trick but why https://preactjs.com/guide/switching-to-preact suggest me to add this btw?
```js
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "h" }]
  ]
}
```
So it's required or not required then in case it already alias? Or maybe for other use case?

Thanks

**Comment by developit** [comment]
Ah I see - yeah that guide is actually two separate options. If you do preact-compat, you don't need the alias.  I should make that clearer!

**Comment by katopz** [comment]
Na it's my bad! I just skip reading, blame my bad habit 💨  Thanks!

**Comment by samueleaton** [comment]
@developit should there be a note in the README? It tripped me up too. 😥

**Comment by developit** [comment]
Happy to merge a PR for that if you have good wording to put around it.

**Comment by davesnx** [comment]
Should we make it a little bit clearer on the README? 

Adding a NOTE comment below the Babel way that If you are using webpack resolve alias don't need the transform with h?

**Comment by developit** [comment]
Sure, would be happy to merge a clarification there.

**Comment by VincentCharpentier** [comment]
Not sure if this is good practice, but adding this plugin to webpack config solve the issue:

```javascript
new webpack.ProvidePlugin({
  h: ['preact', 'h'],
})
```

That way whenever webpack encounter a usage of `h` it will import it for you.
The solve the issue where linter would tell me "h" is imported without being used.

**Comment by marvinhagemeister** [comment]
@valoricDe Not sure I follow your line of thinking. All that babel does is turn this:

```jsx
<div>foo</div>
```

...into:

```js
h("div", null, "foo");
```

So if you're using JSX, setting up the babel plugin is necessary.

Now if you're interested in using third party libraries written for React the bundler that you're using needs to be aware of the fact that you want to use Preact instead of React. That's what aliasing is for. If you don't need React compatibility in your project, you can omit this step.

**Comment by valoricDe** [comment]
@marvinhagemeister I try to elaborate: If I establish the alias to preact/compat all places where it normally would use react it uses preact/compat. preact/compat exposes a function called createElement to be inline with the interface of react. But if we also add 
```
["@babel/plugin-transform-react-jsx", {
      "pragma": "h",
      "pragmaFrag": "Fragment",
    }]
```
Babel is using the function h instead of createElement. Then my application is then erroring: `Uncaught ReferenceError: h is not defined`.
So my question is: does preact/compat also expose the function h? And if not, which module would expose the function h?

**Comment by marvinhagemeister** [comment]
@valoricDe right, I see where the confusion is coming from. The `h` function is exactly the same as `createElement`. They are an alias of each other. We only export `createElement` from compat. Initially we only ever had `h()` in Preact, because of hyperscript, which was kinda a precursor to the JSX that is known today. It's often used in "pure" Preact apps because it's shorter to type.

We should update the docs for that though to make it more clear.
