### ISSUE TITLE
use with react-addons-shallow-compare

### ISSUE THREAD

**Issue by JoeMattie** [developit/preact-compat#18]
I haven't looked at it closely, but this might be same issue as #14

**Comment by developit** [comment]
@JoeMattie `npm install react-addons-shallow-compare` doesn't work?  That package just seems to be a basic diff: https://github.com/facebook/react/blob/master/src/addons/shallowCompare.js

Not sure why it wouldn't work, since it doesn't depend on React or anything.

**Comment by tkh44** [comment]
The problem is that shallowCompare requires 'shallowEqual' from 'react/lib/shallowEqual'.

You can easily create your own version with something like:

```
import shallowequal from 'shallowequal';

const shallowCompare = (instance, nextProps, nextState) => {

    return (
        !shallowequal(instance.props, nextProps) ||
        !shallowequal(instance.state, nextState)
    );
};

export default shallowCompare;
```

I also wrote a little lib to take care of this The problem is that shallowCompare requires 'shallowEqual' from 'react/lib/shallowEqual'.

You can easily create your own version with something like:

```
import shallowequal from 'shallowequal';

const shallowCompare = (instance, nextProps, nextState) => {

    return (
        !shallowequal(instance.props, nextProps) ||
        !shallowequal(instance.state, nextState)
    );
};

export default shallowCompare;
```

I also wrote a little lib to take care of this 
https://www.npmjs.com/package/preact-shallow-compare

**Comment by developit** [comment]
@tkh44 Awesome work. We should get this added to the preact website. I can make a new section for "Libraries & Add-ons".

**Comment by TheNeikos** [comment]
For those struggling with a similar error due to a dependency using this package (and are new to webpack), you have to add this line to your `webpack.babel.js`:

```js
alias: {
   /* Other stuff */
   'react-addons-shallow-compare': 'preact-shallow-compare'
}
```

**Comment by tkh44** [comment]
@TheNeikos I would use the https://github.com/tkh44/shallow-compare. I depreciated preact-shallow-compare in favor of the more generic name.
