### ISSUE TITLE
aframe-react won't re-render correctly

### ISSUE THREAD

**Issue by Zacqary** [developit/preact-compat#230]
`preact-compat` doesn't seem to work with the React bindings to A-Frame: https://github.com/ngokevin/aframe-react

This code is supposed to render a sphere in the scene, wait 1500 seconds, and then increase the sphere's radius to `2`:

``` javascript
import 'aframe';
import { Scene, Entity } from 'aframe-react';

export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = { radius: 0.5 };
    }
    componentDidMount() {
        setTimeout(() => {
            this.setState({ radius: 2 });
        }, 1500);
    }
    render() {
        return (
            <div id="app">
                <Scene>
                    <a-sphere position="0 1.5 -15"
                             color="red"
                             radius={this.state.radius}/>;
                </Scene>
            </div>
        );
    }
}
```

In React this works fine, but Preact just clears the scene entirely. This same issue seems to cause hot-reloading not to work in Preact.

**Comment by developit** [comment]
I put together a demo to verify and it looks like this is because aframe-react is relying on preact ignoring nodes it didn't create, which is not the current behavior (generally, shouldComponentUpdate is used for that). However, there are a fair few open issues pointing to modifying preact to intentionally ignore extra nodes in the DOM. I think that's the best solution here too.

**Comment by developit** [comment]
@Zacqary Happy to announce this will be fixed in the next release!

Here's your demo working:

![31fd1e0159ba4c018b0946a761c94366](https://cloud.githubusercontent.com/assets/105127/20045131/9986abc2-a46c-11e6-9b46-c053069e873b.gif)

**Comment by developit** [comment]
Working via preact@beta!
