### ISSUE TITLE
Handle unmet react peerDependencies

### ISSUE THREAD

**Issue by stephenjwatkins** [developit/preact-compat#243]
I was wondering if you have been able to come up with a reasonable method for suppressing the "unmet peer dependency" errors that come with depending on libraries that have a `peerDependency` on **React**, but want to use solely with **preact-compat**.

![image](https://cloud.githubusercontent.com/assets/752942/20681210/9b1ce3a6-b570-11e6-9e74-30b5bc6c076c.png)

Has it been just a matter of biting the bullet and ignoring the errors at this point, or is there a better way to handle this situation?

(By the way, I love the work that's being done with preact.)

**Comment by developit** [comment]
That's an interesting case.  I know there has been some work done to fix this by using namespace packages. Other than that I'm not sure how to approach it.

**Comment by developit** [comment]
So @iamale actually found an incredibly clever solution for people who either don't want to alias (via webpack, etc), or are annoyed by the errors/warnings you noted relating to peer dependencies.  He created a Github org called `preact-compat`, and published two repos there: `react` and `react-dom`.  Since `npm` allows modules to be installed from git, and those modules can be named anything they want (not subject to the uniqueness constraint in the public npm registry), those two packages can be installed *as* react and react-dom, rather than alias targets.  It's very clever and I think solves this problem for those who want it:

https://github.com/preact-compat/react

I think I will close this issue out since there's now a way to circumvent the warnings, but I'm happy to keep discussing options.

**Comment by iamale** [comment]
(You still need to install `preact-compat` itself first, though!)

**Comment by developit** [comment]
Ahh yes, I'll update my comment. +1 for using `peerDependencies` for this!

**Comment by stephenjwatkins** [comment]
@iamale Very clever indeed! @developit I appreciate you looking into this.
