### ISSUE TITLE
Recommended way to author (bundle & package) a React like library in 2017

### ISSUE THREAD

**Issue by lorenzofox3** [developit/preact-compat#315]
Hi, 

I saw you pointed to [Eric Elliot gist](https://gist.github.com/ericelliott/7e05747b891673eb704b) which uses a factory to treat React as an external dependency. But I wanted to know your opinion on how to package/bundle a new library (component or higher order component) to make sure it is easily reusable by the different communities of React like frameworks (React, Preact, Inferno, etc). 

Thanks.

**Comment by developit** [comment]
I think for a certain class of components, Eric's DI suggestion is quite well-suited.  However, I've found it's difficult to sell people on having to construct a component rather than just importing and using it.

I think an ideal case (which I've not yet tried myself) would be to go the factory route, but then ship *-react, *-preact etc versions of the component that are just invocations of that factory against peerDependencies:

```js
// box.js
export default ({ createElement, Component }) =>
  class Box extends Component {
    render() {
      return (
        <div className="box">
          <h1>{this.props.title</h1>
        </div>
      );
    }
  }


// /react.js
import box from '.';
import React from 'react';
export default box(React);


// /preact.js
import box from '.';
import preact from 'react/aliases';
export default box(preact);
```

**Comment by lorenzofox3** [comment]
Great thanks. In my case my library is more a set of "behaviors" (as higher order component) so the factory is anyway in the spirit of the library. I'll try as you said to provide a version per framework, it seems pretty good.
