### ISSUE TITLE
Getting <undefined></undefined> when trying to switch to preact-compat

### ISSUE THREAD

**Issue by grimunit** [developit/preact-compat#328]
I spent quite a long time trying to figure out why my render method was just spitting out a `<undefined></undefined>` component with no error or warning as to why that was the case.

Turns out that I was using the babel plugin `"transform-react-inline-elements"` which doesn't play nicely with preact-compat and will just return that `<undefined>` tag.  So if you're using that plugin when switching, make sure to remove it.

Thanks to @tkh44 and @developit for helping me out with this on the preact-compat slack channel.

**Comment by developit** [comment]
Definitely worth getting some documentation around this, but I think we can also try to address it in Preact's core too by [fixing this @todo item](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L105) so that `undefined` components throw errors.  That way you'd get a stack trace at least :)

**Comment by mauron85** [comment]
There many other examples. Like you cannot using wepack DLL bundles or at least you cannot put following into the DLL bundle (react-redux, react-star-rating-component, rebass, react-intl, ...) Not sure why? It means that hot reload take significantly more time then using vanilla react.

Also you cannot use optimizers like babel-react-optimize.

**Comment by developit** [comment]
Not sure I follow @mauron85, but I'll try to answer to the best of my abilities. The DDL bundle issue has nothing to do with Preact, that's just how DLLs work in Webpack - they can't be aliased.  Hot reloading shouldn't be affected by that since HMR only updates changed modules.

`babel-react-optimize` is actually exactly the same issue here - it's a preset that happens to include `babel-plugin-transform-react-constant-elements`.  FWIW, that transformation is unlikely to have any effect on Preact's performance in the first place, so it's just adding complexity that isn't needed.

**Comment by mauron85** [comment]
>...they can't be aliased

I'm actually wondering, why those modules cannot be in DLL like with react. Is preact-compat doing some kind of monkey patching? Or what do you mean by 'they can't be aliased'?

**Comment by developit** [comment]
Webpack's DLLPlugin does not respect aliases (see explanation in webpack/webpack#2374).  It creates a standalone bundle that exports a require-like function for loading modules, and that function does not take your webpack bundle's aliases into account.

There is a [very long explanation here](http://stackoverflow.com/questions/39941187/how-do-i-include-npm-modules-in-webpack-dlls).

So, while this has nothing to do with preact/preact-compat, the reason it works in react is because you're not using any aliases.

If you want it to work out-of-the-box, you should be able to use the alternative technique for including `preact-compat`. There's a great explanation how to do that here:
https://github.com/preact-compat/react

Doing so eliminates the need for any aliasing at all, instead using namespaced proxy modules.

**Comment by mauron85** [comment]
thank u, that is the exact explanation i was looking for

**Comment by mauron85** [comment]
One last question. Can this somehow be solved with babel-plugin-module-resolver instead of webpack aliases?

**Comment by developit** [comment]
Awesome, sorry I got confused! 😇

Unfortunately, `babel-plugin-module-resolver` being a babel plugin means it's only run on your code (unless you're running babel on all of your `node_modules` dependences, which most people don't).

**Comment by mauron85** [comment]
Didn't thought that. But as I do know, IMO hot reloads would probably even slower and my experience is that different .babelrc configuration lead to conflicts between main app and node_modules, preventing even from building it.

**Comment by developit** [comment]
We recursively run Babel on any ES2015 dependencies and just turn off `.babelrc` support via the `babelrc` option in `babel-loader`.

**Comment by developit** [comment]
undefined will warn in the next version of preact :)

**Comment by stevefan1999** [comment]
I worked on reverting what 'transform-react-inline-elements' has done, and it's somewhat (partially) working. My app ran but animation states are still messed up. 

Testers and suggestions are welcomed.

https://github.com/stevefan1999/fuck-babel-helper-jsx
