### ISSUE TITLE
deprecated proptype validation cannot be disabled by environment state

### ISSUE THREAD

**Issue by MichaelRando** [developit/preact-compat#354]
Latest node_modules/prop-types/checkPropTypes.js doesn't like the prop type validations. I cannot turn them off because DEV is hardcoded true via:
`const DEV = typeof process==='undefined' || !process.env || process.env.NODE_ENV!=='production';`

I don't use a mock process lib in the browser, so there's not a easy string substitution that will toggle off that DEV=true. 

The warning text is 
`Warning: You are manually calling a React.PropTypes validation function for the 'store' prop on 'Provider'. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
`

**Comment by developit** [comment]
Hmm - `prop-types` isn't yet used by `preact-compat`, it seems like you wanted [proptypes](https://npm.im/proptypes):

`<script src="//unpkg.com/proptypes"></script>`

With that you won't see the warning. We're looking at switching to the new module in #351 & #352, but due to that warning we've not yet made the move.

**Comment by lukeed** [comment]
Probably can be closed, we've moved to `prop-types` module.
