### ISSUE TITLE
How can I know what version of React that it compatible with?

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat#36]
Just curious.

**Comment by developit** [comment]
Hmm. This poses an interesting question! Ideally, since the cost has seemed to stay relatively low, `preact-compat` aims to support arbitrary version of React's API. Obviously the implementation details differ internally anyway, so changes in React relating to how they render certain things (not collapsing spans, unwrapping text nodes, etc) don't really affect preact-compat. 

The one case I can think of where this would be difficult or impossible to support would be if an existing React API were to be changed in a wholely backwards-incompatible way, and the usage could not be automatically detected. A purely hypothetical example would be if React changed the `children` property to always be an Array. This would have to constitute a major version increment for `preact-compat`, since the previous functionality couldn't be supported alongside the new.

In a case where this happens, it will be important to begin calling out API version compatibility explicitly in the readme. For now, it eould be same to say preact-compat aims to be API-compatible with React 0.13+.

Hope that helps answer your question!

**Comment by katopz** [comment]
Thanks for info, I just read this https://facebook.github.io/react/blog/2016/04/07/react-v15.html and it raise my concern about campatible with preact. 

And yes, it would be nice if you note this in readme :)

Cheers

**Comment by developit** [comment]
Some interesting notes from there btw:

- React 15's initial render now works the same way Preact's always has (document.createElement)
- Peact's SVG support is perhaps more similar to how SVG now works in React 15 since it does not use static lists of elements/attributes
- Preact has always used DOM TextNodes for text in JSX, as React 15 now does. Preact actually even collapses adjacent Text nodes for performance.

Overall, I'm pretty happy to see these changes come to React, since they are all making the two more similar in terms of their behavior. :)
