### ISSUE TITLE
Reusing nodes should not retain the class list

### ISSUE THREAD

**Issue by bionicbrian** [developit/preact-compat#365]
In v3.15.0, it appears that render reuses the first child of the target node _and_ its class list? But _only_ when the first element of the react component tree does _not_ have a class list?

Simply applying `className=""` to the first element of the top-level React component solves the error, but should probably not be necessary?

This can cause some weird styling due to unexpected CSS inheritance. 

Example:
https://codepen.io/bionicbrian/pen/GmpzVP

I think this may be related to this preact issue: https://github.com/developit/preact/issues/544 ?

**Comment by bionicbrian** [comment]
Also! Looks like it only happens in combination with `preact@8.1.0`. So `preact-compat@3.15.0` + `preact@7.2.0` is good, but with 8.1.0, not so much.

**Comment by developit** [comment]
This seems to have been caused by this optimization:
https://github.com/developit/preact/commit/25f462b315f307a56f7a59265eeffadcd8569722#diff-a0896fa5d65b1d80ca4d496badbae50fL130

Since there is no `class` / `className` prop in the client-rendered VDOM, the `class` attribute is never diffed and thus never removed.  That's why adding an empty prop works.  Good catch!

Maybe we should move this issue to the preact repo?

**Comment by bionicbrian** [comment]
@developit ah! thanks. I can copy this over to a new issue in the preact repo.
