### ISSUE TITLE
Single element children

### ISSUE THREAD

**Issue by jmatsushita** [developit/preact-compat#401]
Hi there,

This might not be related to preact-compat but I wanted to run this by you before trying to work on a reproduction with preact-compat to check this.

When interoperating with a purescript library (which compiles to javascript) I run into a problem with a library that expects the children props to have a `forEach` method.

The issue alexmingoia/purescript-pux#132 and for convenience how the console shows the children props for preact and react:

In preact the console shows:
![image](https://user-images.githubusercontent.com/356097/27591104-0249b302-5b51-11e7-99c2-f65fba2877e0.png)

While in react:
![image](https://user-images.githubusercontent.com/356097/27591128-11e39882-5b51-11e7-81ac-0db81c8b56aa.png)

Looking at [the code here](https://github.com/developit/preact-compat/blob/master/src/index.js#L507), it seems that you're trying to pretend that a single element children prop is an array but not including Array prototype methods like `forEach`.

React on the other hand seems to return a proper Array (or something indistinguishable from it) for single element children.

Is that something that should be fixed here?

Cheers,

Jun

**Comment by developit** [comment]
React just preserves whatever is passed to `createElement()`, so you're likely seeing something that purescript generated (whereas JSX would not normally generate that).

I think what we can do is switch [this bit of code](https://github.com/developit/preact-compat/blob/master/src/index.js#L505-L511) to copy the VNode properties onto an Array rather than adding `[0]` to the VNode (maybe).

**Comment by marvinhagemeister** [comment]
With Preact X we aligned with react for greater compatibility. This means that there is no guarantee anymore that children will always be of type array.
