### ISSUE TITLE
Dont' work with git version of preact

### ISSUE THREAD

**Issue by koutsenko** [developit/preact-compat#469]
I've installed latest preact version
npm install git+https://github.com/developit/preact.git

It installs successfully, but when i try to build project, i get an error:

ERROR in ./node_modules/preact-compat/dist/preact-compat.es.js
Module not found: Error: Can't resolve 'preact' in 'C:\******\node_modules\preact-compat\dist'

**Comment by koutsenko** [comment]
Thanks for the comment, Marvin. Is there any way to get preact with working HMR today? Latest published 1.2.7 version doesn’t work with it.

**Comment by marvinhagemeister** [comment]
@koutsenko If there isn't already an open issue with HMR feel free to file a new one with steps to reproduce the problem you are experiencing.

**Comment by marvinhagemeister** [comment]
HMR is implemented by third party libraries like `react-hot-loader` not by frameworks themselves (eg react/preact/whatever). Best to file an issue on their repository.

Although we do try to support as much of the react ecosystem as we can, we can keep track of any change done in a third party library. That's why such a list would not make sense because it would always be out of date with the rate of changes coming each day.

**Comment by kevlened** [comment]
I'm using https://github.com/developit/preact-cli with the https://github.com/preactjs-templates/material template and HMR works. Try comparing your setup to that one.

**Comment by developit** [comment]
I believe there are already multiple issues open about HMR. React Hot Loader is (was?) assuming module boundaries were mutable, which isn't the case if you're using an ES Modules bundler like Rollup or Webpack 4.  That issue has little/nothing to do with Preact, and more to do with RHL.
