### ISSUE TITLE
findDOMNode returning null

### ISSUE THREAD

**Issue by ttches** [developit/preact-compat#499]
This code is working in v3.18.0, but @latest, findDOMNode is returning null even though I can console.log the component I'm passing in.

<img width="479" alt="screen shot 2018-08-20 at 10 04 46 am" src="https://user-images.githubusercontent.com/15929691/44355348-37380000-a461-11e8-8fd1-34c5e1dc3da8.png">

![screen shot 2018-08-20 at 10 06 45 am](https://user-images.githubusercontent.com/15929691/44355374-46b74900-a461-11e8-92fa-0b784b094b10.png)

**Comment by pl12133** [comment]
@ttches When you say `@latest`, could you confirm you have `3.18.3` installed?

This was broken by ad59cf3e9f80c48027d7df12c322c0d27fccccf7 in [`3.18.1`](https://github.com/developit/preact-compat/compare/3.18.0...3.18.1) but it should have been fixed by ff884c95a2151f95bccf3f6d1675c49709bc0dfe in [`3.18.3`](https://github.com/developit/preact-compat/releases/tag/3.18.3).

**Comment by ttches** [comment]
I think I deleted node_modeules and reinstalled with 3.18.3 and it's working now. Thank you!
