### ISSUE TITLE
Export hooks

### ISSUE THREAD

**Issue by dy** [developit/preact-compat#524]
Just followed the transition guide https://preactjs.com/guide/switching-to-preact, and getting an error that `useCallback` hook is not defined. There seems to be no docs in preact/preact-compat about hooks so far.

Any chance we can get `import React, {useState, useMemo} from 'preact-compat'` soon?

**Comment by marvinhagemeister** [comment]
It's already there just under a different import. The package `preact-compat` (note the minus sign) is for Preact 8.x. For our next major release Preact X we moved compat into core and can be imported via `preact/compat`.

Because X is still in alpha we haven't updated our docs. Once X is marked as stable we'll update our accordingly. Doing it now would confuse users because npm points to Preact 8.x by default. The alpha on the other hand can only be installed when the user specifically opts in to that.
