### ISSUE TITLE
babel-core may be outdated

### ISSUE THREAD

**Issue by fsultani-aspiration** [developit/preact-compat#530]
[`@babel/core`](https://github.com/babel/babel/blob/master/packages/babel-core/package.json#L3) lists `7.4.5` as the current version, yet `preact-compat` is using `^6.26.3`.  Is this outdated?

I keep getting an error in my app:
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```
I'm wondering if they're related.

**Comment by marvinhagemeister** [comment]
That error is not caused by `preact-compat`. We only use babel during development itself. Users will never install it as because it's flagged as a `devDependency`. The most likely cause it's that you have some other dependency in your project which marked dependencies intended for development incorrectly. You can check who installed it with yarn via `yarn why babel-core`. There is a similar command for npm, but I don't know off the top of my head how it is called. A quick Google search should point you to it.
